name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create upm branch
        uses: RageAgainstThePixel/upm-subtree-split@v1
      - name: Create upm git tag
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git tag $TAG upm
          git push origin --tags
        env:
          TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
